name: demo

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  save-time:
    runs-on: ubuntu-latest
    steps:
      - name: Set outputs
        id: vars
        run: echo "::set-output name=production::true"
  
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.production }}
        
  get-time:
    needs: save-time
    runs-on: ubuntu-latest
    steps:
      - name: Check outputs v2
        run: echo ${{ steps.vars.outputs.production }}
