name: demo

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  save-time:
    runs-on: ubuntu-latest
    steps:
      - uses: nick-invision/persist-action-data@v1
        with:
          data: ${{ steps.some-step.output.some-output }}
          variable: SOME_STEP_OUTPUT
  
      - uses: nick-invision/persist-action-data@v1
        with:
          data: ${{ steps.some-step.output.some-output }}
          retrieve_variables: SOME_STEP_OUTPUT, SOME_OTHER_STEP_OUTPUT
      - run: echo $SOME_STEP_OUTPUT
        
  get-time:
    needs: save-time
    runs-on: ubuntu-latest
    steps:
     - uses: nick-invision/persist-action-data@v1
       with:
          data: ${{ steps.some-step.output.some-output }}
          retrieve_variables: SOME_STEP_OUTPUT, SOME_OTHER_STEP_OUTPUT
     - run: echo $SOME_STEP_OUTPUT
