name: .NET Core CI

on:
  push:
    branches: [ master ]

  # Manual trigger using web interface (github.com)
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

env:
  DOTNET_VERSION: '3.1.x'
  
  
jobs:
  codecov_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Setup .NET Core
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Install dependencies
        run: dotnet restore
     
      - name: Build   
        run: dotnet build -warnaserror --configuration Release --no-restore
