name: Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:
      inputs:
        logLevel:
          description: 'Log level'     
          required: true
          default: 'warning'
        tags:
          description: 'Test scenario tags'

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
      - run: echo "Deployed"
